### ISSUE TITLE
Syntax error in schema

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/wxflow#11]
**Expected behavior**
Code should pass pynorm check.

**Current behavior**
pynorm fails due to a syntax error in schema.py:

```
src/wxflow/schema.py:609:46: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
```

**Machines affected**
N/A

**To Reproduce**
1. Run pycodenorm GH action

**Context**
First reported by @jkhender (in global-workflow before the script was moved).

Script previously passed the check, so this seems like an update to pycodenorms.

**Detailed Description**

**Additional Information**

**Possible Implementation**
Offending line should be changed to
```
                elif flavor == VALIDATOR and isinstance(s, Regex):
```

**Comment by aerorahul** [comment]
fixed by #15
