### ISSUE TITLE
Replace single-character variables in schema with more descriptive names

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/wxflow#12]
**Description**
[schema.py](https://github.com/NOAA-EMC/wxflow/blob/develop/src/wxflow/schema.py) uses single-character variables in places when more descriptive variables names would be better.

**Requirements**
Variable names should be descriptive enough to know what they are without seeing the declaration. Single-character names are especially problematic because they are also difficult to search for.

**Acceptance Criteria (Definition of Done)**
All vague variable names replaced with more descriptive names.

**Dependencies**
None

**Comment by aerorahul** [comment]
@WalterKolczynski-NOAA 
`schema.py` has been fork-lifted for convenience and we have tried to keep it as close as possible to the original (exception fixing pycodestyle errors) to allow easy updates if/when the code needs to be synced with upstream.
