### ISSUE TITLE
Executable class `error` file path is binary format.

### ISSUE THREAD

**Issue by HenryRWinterbottom** [NOAA-EMC/wxflow#13]
The executable class `Executable` writes a binary formatted file when `error` is defined at run time. This is the standard error file and is thus unreadable.

**Expected behavior**
The contents of the `error` file path should be readable.

**Current behavior**
Currently the contents of the `error` file path are unformatted (e.g., binary).

**Machines affected**
All, including OSX.

**Comment by aerorahul** [comment]
Can you provide a code snippet demonstrating this bug?
