### ISSUE TITLE
Is it possible to relax the jinja requirements

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/wxflow#37]
This:
https://github.com/NOAA-EMC/wxflow/blob/d314e065101041a4d45e5a11ec19cd2dc5f38c67/setup.cfg#L45
is causing spack-stack headaches, because other components of the unified environment require earlier versions of jinja (`3.0.3`). Can someone please check if `wxflow` works with `jinia>=3`? Thanks!

**Comment by aerorahul** [comment]
@climbfuji 
I don't think this will be an issue, but I will check and confirm.

**Comment by climbfuji** [comment]
@aerorahul Did you have a chance to check if wxflow works with earlier versions of jinja2?

**Comment by aerorahul** [comment]
@climbfuji 
We are using a feature `pass_eval_context` from `jinja2` 3.1.0.  I can try 3.1.0 instead of 3.1.2 if you would like.

**Comment by aerorahul** [comment]
Another utility used in the GDASapp [jcb](https://github.com/NOAA-EMC/jcb) is also using `jinja2 >= 3.1.2`.

**Comment by climbfuji** [comment]
Ok, thanks for checking Rahul. We'll keep the newer version and work in fixing whatever wants the old version.
